### ISSUE TITLE
webpack

### ISSUE THREAD

**Issue by jehoshua02** [slcfwd/topics#5]
http://webpack.github.io/

My favorite benefits of Webpack:
- Organize front-end javascript into [CommonJS](http://wiki.commonjs.org/wiki/Modules/1.1) modules.
- Compile [Sass](http://sass-lang.com/).
- Compile [React.js JSX](http://facebook.github.io/react/docs/displaying-data.html#jsx-syntax).
- Compile everything into a few page script and a site specific script.
- Optimization: common chunk and uglification.

**Comment by jehoshua02** [comment]
I vote for this one. :+1:

**Comment by andrewdavid11** [comment]
I am interested in this one eventually also.
