### ISSUE TITLE
Javascript Modules

### ISSUE THREAD

**Issue by jehoshua02** [slcfwd/topics#6]
Talk about what javascript modules are and different formats and what build tools can be used to achieve modules in front-end code.

Edit: CommonJS, AMD, UMD, ES6.

**Comment by trevordmiller** [comment]
I vote for this topic next :+1:

**Comment by jehoshua02** [comment]
@trevordmiller Would you like to see the topic refined in any direction, or just an overview?

**Comment by jehoshua02** [comment]
@trevordmiller Such as really digging into a specific build tool to compile javascript modules?

**Comment by trevordmiller** [comment]
@jehoshua02 Well, I might not be able to attend the next few meetings so I wouldn't base the decision on me...but personally, I love digging into vanilla JS design patterns and whatnot: http://addyosmani.com/resources/essentialjsdesignpatterns/book/ ;)

I am not too interested in all the meetups discussing the latest and greatest libraries and frameworks. I like me some good ol' native JS, HTML, and CSS ;) Maybe a bit of "standard" tools like Grunt, Sass, Git, etc.

**Comment by jehoshua02** [comment]
@trevordmiller Adjusting the date/time may be a possibility if it would allow more people to come.

**Comment by sevenstreak** [comment]
I'm good with anything. This is my first meetup so...

**Comment by ryanlfoster** [comment]
This one gets my vote. I always chuckle a little bit whenever I see a job posting by an HR rep that says "must know _______ (insert latest JS buzzword here i.e AngularJS, Backbone, JQuery, Knockout, MooTools)... If you have a solid understanding of Essential Design Patterns and how vanilla javascript works, its pretty easy to figure out any framework with a little bit of study.

**Comment by jehoshua02** [comment]
@ryanlfoster @trevordmiller For this topic, I was thinking [Modern Modular JavaScript Design Patterns](http://addyosmani.com/resources/essentialjsdesignpatterns/book/#modularjavascript), or what I like to refer to as "true modules". Is that what you were thinking? Or by "vanilla javascript" did you mean the [Module Pattern](http://addyosmani.com/resources/essentialjsdesignpatterns/book/#modulepatternjavascript) and [Revealing Module Pattern](http://addyosmani.com/resources/essentialjsdesignpatterns/book/#revealingmodulepatternjavascript)?

**Comment by jehoshua02** [comment]
We talked about this a bit at the last meetup so I'm gonna close. That doesn't mean it can't come up again though.
